package com.appsys.mapper;

import java.util.List;

import com.appsys.pojo.AppCategory;

public interface AppCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Wed Jun 17 11:32:14 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Wed Jun 17 11:32:14 CST 2020
     */
    int insert(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Wed Jun 17 11:32:14 CST 2020
     */
    int insertSelective(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Wed Jun 17 11:32:14 CST 2020
     */
    AppCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Wed Jun 17 11:32:14 CST 2020
     */
    int updateByPrimaryKeySelective(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Wed Jun 17 11:32:14 CST 2020
     */
    int updateByPrimaryKey(AppCategory record);
    
    /**
     * 获取 一二三级分类
     * @return
     */
    List<AppCategory> listCategorylevel1();
    List<AppCategory> listCategorylevel2(Integer parentId);
    List<AppCategory> listCategorylevel3(Integer parentId);
    
}