package com.appsys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.appsys.pojo.AppInfo;

public interface AppInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int insert(AppInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int insertSelective(AppInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	AppInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int updateByPrimaryKeySelective(AppInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int updateByPrimaryKey(AppInfo record);
	
	/**
	 * 按调价搜索应用 分页
	 * @param appInfo
	 * @param pageIndex
	 * @param pageSize
	 * @return
	 */
	List<AppInfo> search(AppInfo appInfo);
}