package com.appsys.mapper;

import com.appsys.pojo.AppInfo;

public interface AppInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 16:45:22 CST 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 16:45:22 CST 2020
	 */
	int insert(AppInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 16:45:22 CST 2020
	 */
	int insertSelective(AppInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 16:45:22 CST 2020
	 */
	AppInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 16:45:22 CST 2020
	 */
	int updateByPrimaryKeySelective(AppInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_info
	 * @mbggenerated  Fri Jun 19 16:45:22 CST 2020
	 */
	int updateByPrimaryKey(AppInfo record);
}