package com.appsys.mapper;

import java.util.List;

import com.appsys.pojo.AppVersion;

public interface AppVersionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int insert(AppVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int insertSelective(AppVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	AppVersion selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int updateByPrimaryKeySelective(AppVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version
	 * @mbggenerated  Fri Jun 19 17:35:16 CST 2020
	 */
	int updateByPrimaryKey(AppVersion record);
	
	/**
	 * 根据app的id查出历史一共的版本列表
	 * @param appid
	 * @return
	 */
	List<AppVersion> findAppId(Long appid);
	
	
	//根据应用的id删除对应的版本
	int deleteByAppId(Long appid);
}